name: Go Lint
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.golangci.yaml'
      - '.github/workflows/go-lint.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.golangci.yaml'
      - '.github/workflows/go-lint.yaml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.23.x'

    - name: Lint SDK
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        working-directory: sdk/go
        args: --timeout 3m --verbose

    - name: Lint Root
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        args: --timeout 3m --verbose
